/* Generated Code (IMPORT) */
/* Source File: THESIS COUNTRY DATA.xlsx */
/* Source Path: /home/u63737437/sasuser.v94 */
/* Code generated on: 4/23/25, 1:10 PM */

%web_drop_table(WORK.IMPORT);


FILENAME REFFILE '/home/u63737437/sasuser.v94/THESIS COUNTRY DATA.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.COUNTRIES;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.COUNTRIES; RUN;


%web_open_table(WORK.IMPORT);

data countries_clean;
    set COUNTRIES;
    if cmiss(of _all_) = 0;
run;

Data COUNTRIES2;
 set countries_clean;
 
 if HPV_VACCINE='Not routinely administered' then do;
 	x1=1; x2=0;
 	end;
 else if HPV_VACCINE='Regions of the country' then do;
 	x1=0; x2=1;
 	end;
 else do;
 	x1=0; x2=0;;
 	end;
Data COUNTRIES3;
 set COUNTRIES2;
 
 if HEPATITISB_VACCINE='Specific risk groups' then do;
 	y1=1; y2=0;
 	end;
 else if HEPATITISB_VACCINE='Adolescents' then do;
 	y1=0; y2=1;
 	end;
 else do;
 	y1=0; y2=0;;
 	end;
 	
 	
proc reg data=COUNTRIES3;
model INCIDENCE = SMOKING ALC_CONSUMPTION HDI OBESITY UNDERNOURISHMENT HIGHSCHOOL_DIPLOMA SUGAR_CONSUMPTION_PER_CAPITA GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE AIR_POLLUTION MEAN_HOUSEHOLD_INCOME "WATER QUALITY"n UNEMPLOYMENT_RATE x1 x2 y1 y2/vif;
run;
/*some major multicollinearity >>> ridge regression*/




/*INITIAL MODELS*/

/*note stepwise and forward produce same model so we will move forward with just stepwise*/

/*STEPWISE<unimproved>*/
proc reg data=COUNTRIES3;
model INCIDENCE = SMOKING ALC_CONSUMPTION HDI OBESITY UNDERNOURISHMENT HIGHSCHOOL_DIPLOMA SUGAR_CONSUMPTION_PER_CAPITA GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE AIR_POLLUTION MEAN_HOUSEHOLD_INCOME "WATER QUALITY"n UNEMPLOYMENT_RATE x1 x2 y1 y2/selection=stepwise slentry=.05 slstay=.05;
run;
/*FORWARD<unimproved>*/
proc reg data=COUNTRIES3;
model INCIDENCE = SMOKING ALC_CONSUMPTION HDI OBESITY UNDERNOURISHMENT HIGHSCHOOL_DIPLOMA SUGAR_CONSUMPTION_PER_CAPITA GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE AIR_POLLUTION MEAN_HOUSEHOLD_INCOME "WATER QUALITY"n UNEMPLOYMENT_RATE x1 x2 y1 y2/selection=forward slentry=.05 slstay=.05;
run;
/*BACKWARD*/
proc reg data=COUNTRIES3;
model INCIDENCE = SMOKING ALC_CONSUMPTION HDI OBESITY UNDERNOURISHMENT HIGHSCHOOL_DIPLOMA SUGAR_CONSUMPTION_PER_CAPITA GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE AIR_POLLUTION MEAN_HOUSEHOLD_INCOME "WATER QUALITY"n UNEMPLOYMENT_RATE x1 x2 y1 y2/selection=backward slentry=.05 slstay=.05;
run;
/*RIDGE*/
proc reg data=COUNTRIES3 outest=ridge_estimates ridge=0.1 to 1 by 0.5;
   model INCIDENCE = SMOKING ALC_CONSUMPTION HDI OBESITY UNDERNOURISHMENT 
                     HIGHSCHOOL_DIPLOMA SUGAR_CONSUMPTION_PER_CAPITA GDP 
                     "MEDIAN AGE"n WO_HEALTH_INSURANCE AIR_POLLUTION 
                     MEAN_HOUSEHOLD_INCOME "WATER QUALITY"n 
                     UNEMPLOYMENT_RATE x1 x2 y1 y2;
run;


/*LASSO*/
proc glmselect data=COUNTRIES3;
model INCIDENCE = SMOKING ALC_CONSUMPTION HDI OBESITY UNDERNOURISHMENT HIGHSCHOOL_DIPLOMA SUGAR_CONSUMPTION_PER_CAPITA GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE AIR_POLLUTION MEAN_HOUSEHOLD_INCOME "WATER QUALITY"n UNEMPLOYMENT_RATE x1 x2 y1 y2/ selection=lasso(choose=cv stop=none) cvmethod=random(5);
run;



/*INTERACTION TERMS FOR STEPWISE*/
data COUNTRIES3_int;
   set COUNTRIES3;
   INT_UNDERNOURISHMENT_GDP = UNDERNOURISHMENT * GDP;
   INT_GDP_UNEMPLOYMENT_RATE = GDP * UNEMPLOYMENT_RATE;
   INT_UNEMPLOY_UNDERNOURISH = UNEMPLOYMENT_RATE * UNDERNOURISHMENT;
run;
/*STEPWISE*/
proc reg data=COUNTRIES3_int;
model INCIDENCE = UNDERNOURISHMENT GDP UNEMPLOYMENT_RATE INT_UNDERNOURISHMENT_GDP INT_GDP_UNEMPLOYMENT_RATE INT_UNEMPLOY_UNDERNOURISH /selection=stepwise slentry=.05 slstay=.05;
run;

/*INTERACTION TERMS FOR BACKWARD*/
data COUNTRIES3_int2;
   set COUNTRIES3;
   INT_UNDERNOURISHMENT_HDI = UNDERNOURISHMENT * HDI;
   INT_GDP_HDI = GDP * HDI;
   INT_MEDIANAGE_HDI = "MEDIAN AGE"n * HDI;
   INT_INSURANCE_HDI = WO_HEALTH_INSURANCE * HDI;
   
   INT_UNDERNOURISHMENT_GDP = UNDERNOURISHMENT * GDP;
   INT_MEDIANAGE_GDP = "MEDIAN AGE"n * GDP;
   INT_INSURANCE_GDP = WO_HEALTH_INSURANCE * GDP;
   
   INT_UNDERNOURISHMENT_MEDIANAGE = UNDERNOURISHMENT * "MEDIAN AGE"n;
   INT_INSURANCE_MEDIANAGE = WO_HEALTH_INSURANCE * "MEDIAN AGE"n;
   
   INT_UNDERNOURISHMENT_INSURANCE = UNDERNOURISHMENT * WO_HEALTH_INSURANCE;
run;
/*BACKWARD*/
proc reg data=COUNTRIES3_int2;
    model INCIDENCE = INT_UNDERNOURISHMENT_INSURANCE INT_INSURANCE_MEDIANAGE INT_UNDERNOURISHMENT_MEDIANAGE INT_MEDIANAGE_GDP INT_UNDERNOURISHMENT_GDP INT_INSURANCE_HDI INT_MEDIANAGE_HDI INT_GDP_HDI INT_UNDERNOURISHMENT_HDI HDI UNDERNOURISHMENT GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE / selection=backward slentry=0.05 slstay=0.05;
run;




/*SQUARE TERMS FOR STEPWISE*/
data COUNTRIES3_sq;
	set COUNTRIES3;
	UNDERNOURISHMENT_SQ = UNDERNOURISHMENT * UNDERNOURISHMENT;
	GDP_SQ = GDP * GDP;
	UNEMPLOYMENT_RATE_SQ = UNEMPLOYMENT_RATE * UNEMPLOYMENT_RATE;
run;
/*STEPWISE*/
proc reg data=COUNTRIES3_sq;
model INCIDENCE = UNDERNOURISHMENT GDP UNEMPLOYMENT_RATE UNDERNOURISHMENT_SQ GDP_SQ UNEMPLOYMENT_RATE_SQ /selection=stepwise slentry=.05 slstay=.05;
run;


/*SQUARE TERMS FOR BACKWARD*/
data COUNTRIES3_sq2;
   set COUNTRIES3;
	UNDERNOURISHMENT_SQ = UNDERNOURISHMENT * UNDERNOURISHMENT;
	GDP_SQ = GDP * GDP;
	HDI_SQ = HDI * HDI;
	MEDIANAGE_SQ = "MEDIAN AGE"n * "MEDIAN AGE"n;
	INSURANCE_SQ = WO_HEALTH_INSURANCE * WO_HEALTH_INSURANCE;
run;
/*BACKWARD*/
proc reg data=COUNTRIES3_sq2;
    model INCIDENCE = HDI UNDERNOURISHMENT GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE UNDERNOURISHMENT_SQ GDP_SQ HDI_SQ MEDIANAGE_SQ INSURANCE_SQ / selection=backward slentry=0.05 slstay=0.05;
run;




/*INTERACTION AND SQUARE TERMS FOR STEPWISE*/
data COUNTRIES3_int_sq;
   set COUNTRIES3;
   INT_UNDERNOURISHMENT_GDP = UNDERNOURISHMENT * GDP;
   INT_GDP_UNEMPLOYMENT_RATE = GDP * UNEMPLOYMENT_RATE;
   INT_UNEMPLOY_UNDERNOURISH = UNEMPLOYMENT_RATE * UNDERNOURISHMENT;
   UNDERNOURISHMENT_SQ = UNDERNOURISHMENT * UNDERNOURISHMENT;
	GDP_SQ = GDP * GDP;
	UNEMPLOYMENT_RATE_SQ = UNEMPLOYMENT_RATE * UNEMPLOYMENT_RATE;
run;
/*STEPWISE*/
proc reg data=COUNTRIES3_int_sq;
model INCIDENCE = INT_UNEMPLOY_UNDERNOURISH INT_GDP_UNEMPLOYMENT_RATE INT_UNDERNOURISHMENT_GDP UNDERNOURISHMENT GDP UNEMPLOYMENT_RATE UNDERNOURISHMENT_SQ GDP_SQ UNEMPLOYMENT_RATE_SQ /selection=stepwise slentry=.05 slstay=.05;
run;
/*INTERACTION AND SQUARE TERMS FOR BACKWARD*/
data COUNTRIES3_int_sq2;
   set COUNTRIES3;
   INT_UNDERNOURISHMENT_HDI = UNDERNOURISHMENT * HDI;
   INT_GDP_HDI = GDP * HDI;
   INT_MEDIANAGE_HDI = "MEDIAN AGE"n * HDI;
   INT_INSURANCE_HDI = WO_HEALTH_INSURANCE * HDI;
   
   INT_UNDERNOURISHMENT_GDP = UNDERNOURISHMENT * GDP;
   INT_MEDIANAGE_GDP = "MEDIAN AGE"n * GDP;
   INT_INSURANCE_GDP = WO_HEALTH_INSURANCE * GDP;
   
   INT_UNDERNOURISHMENT_MEDIANAGE = UNDERNOURISHMENT * "MEDIAN AGE"n;
   INT_INSURANCE_MEDIANAGE = WO_HEALTH_INSURANCE * "MEDIAN AGE"n;
   
   INT_UNDERNOURISHMENT_INSURANCE = UNDERNOURISHMENT * WO_HEALTH_INSURANCE;
   
   UNDERNOURISHMENT_SQ = UNDERNOURISHMENT * UNDERNOURISHMENT;
	GDP_SQ = GDP * GDP;
	HDI_SQ = HDI * HDI;
	MEDIANAGE_SQ = "MEDIAN AGE"n * "MEDIAN AGE"n;
	INSURANCE_SQ = WO_HEALTH_INSURANCE * WO_HEALTH_INSURANCE;
run;

proc reg data=COUNTRIES3_int_sq2;
    model INCIDENCE = INSURANCE_SQ MEDIANAGE_SQ HDI_SQ GDP_SQ UNDERNOURISHMENT_SQ INT_UNDERNOURISHMENT_INSURANCE INT_INSURANCE_MEDIANAGE INT_UNDERNOURISHMENT_MEDIANAGE INT_MEDIANAGE_GDP INT_UNDERNOURISHMENT_GDP INT_INSURANCE_HDI INT_MEDIANAGE_HDI INT_GDP_HDI INT_UNDERNOURISHMENT_HDI HDI UNDERNOURISHMENT GDP "MEDIAN AGE"n WO_HEALTH_INSURANCE / selection=backward slentry=0.05 slstay=0.05;
run;




/*LASSO INT AND SQ TERMS*/
data COUNTRIES_LASSO;
   set COUNTRIES3;
	UNDERNOURISHMENT_SQ = UNDERNOURISHMENT * UNDERNOURISHMENT;
	GDP_SQ = GDP * GDP;
	AIR_POLLUTION_SQ = AIR_POLLUTION * AIR_POLLUTION;
	x1_SQ = x1 * x1;
	
	UNDERNOURISHMENT_GDP = UNDERNOURISHMENT * GDP;
	UNDERNOURISHMENT_AIR_POLLUTION = UNDERNOURISHMENT * AIR_POLLUTION;
	UNDERNOURISHMENT_x1 = UNDERNOURISHMENT * x1;
	GDP_AIR_POLLUTION = GDP * AIR_POLLUTION;
	GDP_x1 = GDP * x1;
	AIR_POLLUTION_x1 = AIR_POLLUTION * x1;
run;

/*LASSO*/
proc glmselect data=COUNTRIES_LASSO;
model INCIDENCE = AIR_POLLUTION_x1 GDP_x1 GDP_AIR_POLLUTION UNDERNOURISHMENT_x1 UNDERNOURISHMENT_AIR_POLLUTION  UNDERNOURISHMENT_GDP AIR_POLLUTION_SQ GDP_SQ UNDERNOURISHMENT_SQ UNDERNOURISHMENT GDP AIR_POLLUTION x1/ selection=lasso(choose=cv stop=none) cvmethod=random(5);
run;




/*NEXT: test all models for multicollinearity and remove high VIF*/
/*HIGH CORRELATIONS*/
proc reg data=COUNTRIES3;
model INCIDENCE = SMOKING UNDERNOURISHMENT "MEDIAN AGE"n x1 /vif;
run;
/*OG STEPWISE*/
proc reg data=COUNTRIES3;
model INCIDENCE = UNDERNOURISHMENT UNEMPLOYMENT_RATE GDP/vif;
run;
/*OG BACKWARD*/
proc reg data=COUNTRIES3;
model INCIDENCE = UNDERNOURISHMENT GDP x1/vif;
run;
/*OG LASSO*/
proc reg data=COUNTRIES3;
model INCIDENCE = HDI UNDERNOURISHMENT "MEDIAN AGE"n WO_HEALTH_INSURANCE GDP x1/vif;
run;
/*INT STEPWISE*/
proc reg data=COUNTRIES3_int;
model INCIDENCE = INT_GDP_UNEMPLOYMENT_RATE GDP UNDERNOURISHMENT/vif;
run;
/*INT BACKWARD*/
proc reg data=COUNTRIES3_int2;
model INCIDENCE = INT_UNDERNOURISHMENT_INSURANCE INT_MEDIANAGE_GDP HDI "MEDIAN AGE"n WO_HEALTH_INSURANCE/vif;
run;
/*SQ STEPWISE*/
proc reg data=COUNTRIES3_sq;
model INCIDENCE = UNDERNOURISHMENT_SQ UNEMPLOYMENT_RATE GDP/vif;
run;
/*SQ BACKWARD*/
proc reg data=COUNTRIES3_sq2;
model INCIDENCE = GDP HDI_SQ INSURANCE_SQ/vif;
run;
/*INT & SQ STEPWISE*/
proc reg data=COUNTRIES3_int_sq;
model INCIDENCE =  INT_GDP_UNEMPLOYMENT_RATE GDP UNDERNOURISHMENT/vif;
run;
/*INT & SQ BACKWARD*/
proc reg data=COUNTRIES3_int_sq2;
model INCIDENCE = INT_UNDERNOURISHMENT_INSURANCE INT_INSURANCE_HDI INT_GDP_HDI INT_UNDERNOURISHMENT_HDI "MEDIAN AGE"n /vif;
run;
/*INT & SQ LASSO*/
proc reg data=COUNTRIES_LASSO;
model INCIDENCE = x1  GDP UNDERNOURISHMENT_SQ /vif;
run;




/*CHOOSING THE OPTIMAL MODEL*/
proc glmselect data=COUNTRIES3;
model INCIDENCE = SMOKING UNDERNOURISHMENT "MEDIAN AGE"n x1 / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3;
model INCIDENCE = UNDERNOURISHMENT UNEMPLOYMENT_RATE GDP / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3;
model INCIDENCE = UNDERNOURISHMENT GDP x1 / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3;
model INCIDENCE = HDI UNDERNOURISHMENT "MEDIAN AGE"n WO_HEALTH_INSURANCE GDP x1 / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3_int;
model INCIDENCE = INT_GDP_UNEMPLOYMENT_RATE GDP UNDERNOURISHMENT / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3_int2;
model INCIDENCE = INT_UNDERNOURISHMENT_INSURANCE INT_MEDIANAGE_GDP HDI "MEDIAN AGE"n WO_HEALTH_INSURANCE / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3_sq;
model INCIDENCE = UNDERNOURISHMENT_SQ UNEMPLOYMENT_RATE GDP / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3_sq2;
model INCIDENCE = GDP HDI_SQ INSURANCE_SQ / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3_int_sq;
model INCIDENCE = INT_GDP_UNEMPLOYMENT_RATE GDP UNDERNOURISHMENT / selection=none stats=all;
run;

proc glmselect data=COUNTRIES3_int_sq2;
model INCIDENCE = INT_UNDERNOURISHMENT_INSURANCE INT_INSURANCE_HDI INT_GDP_HDI INT_UNDERNOURISHMENT_HDI "MEDIAN AGE"n / selection=none stats=all;
run;

proc glmselect data=COUNTRIES_LASSO;
model INCIDENCE = x1  GDP UNDERNOURISHMENT_SQ / selection=none stats=all;
run;

/*FINAL MODEL*/
proc glmselect data=COUNTRIES3_int;
model INCIDENCE = INT_GDP_UNEMPLOYMENT_RATE GDP UNDERNOURISHMENT / selection=none stats=all;
run;

proc reg data=COUNTRIES3_int;
model INCIDENCE = INT_GDP_UNEMPLOYMENT_RATE GDP UNDERNOURISHMENT;
run;






